### ISSUE TITLE
Improve badges support

### ISSUE THREAD

**Issue by amirouche** [kiwix/sotoki#11]
There is a badges.xml file in the dump look at that or try to dump badges from the API.

**Comment by kelson42** [comment]
How does "badges" work? I had a look to the xml files without understanding the purpose...

**Comment by amirouche** [comment]
Badges are vanity marks of splendor :v:. This is equivalent to achievements in games but most of them are kind of silly IMO. **Badges complete the reputation number**  to know whether the answer of someone can be understood as valuable or not.

The `Badges.xml`:

```xml
  <row Id="1" UserId="1" Name="Organizer" Date="2009-07-15T06:51:46.370" />
```

The `Name` attribute the *Achivement name* but the problem is that in a real StackExchange website this is also associated with a value called rank: `gold`, `silver` or `bronze`. And this rank is required for displaying it correctly in the user page because badges are grouped by rank.

Here is an example output from the API: 

```json
    {
      "badge_type": "named",
      "award_count": 5632,
      "rank": "bronze",
      "badge_id": 222,
      "link": "http://stackoverflow.com/badges/222/altruist",
      "name": "Altruist"
    }
```

As an intermediate solution we can display the total number of badges without grouping by rank.

**Comment by kelson42** [comment]
Thx for the explanation, this seems important to help to evaluate answer. Even if vanity, sounds an added value for the readers.

**Comment by amirouche** [comment]
Will implement the partial support of badges in #6
