### ISSUE TITLE
External links should be tagged

### ISSUE THREAD

**Issue by kelson42** [kiwix/sotoki#13]
External links (so not pointing to a ZIM article) should be visually tagged. This is important for users to make the different between available/non available contents. This is already the case on Wikipedia ZIM files, we use a small icon we put beside the link. I would recommend to take and just tag the external link with a css class (adding this icon on the right of the link).

**Comment by amirouche** [comment]
Got it. I will add it.

**Comment by amirouche** [comment]
It's done only with css. I'll push it later.
