### ISSUE TITLE
Make sure the image offliner and image size reducer are successful

### ISSUE THREAD

**Issue by amirouche** [kiwix/sotoki#17]
During testing on my home machine offlin-ing hangs for some reasons, I don't why. We can't not deliver half backed zim files so make sure to threat this error properly during build

Raise error or log error in case of problem.

**Comment by amirouche** [comment]
Download hangs but no error is raised. When I hit once Ctrl+C the download restarts

**Comment by dattaz** [comment]
Close by #32
