### ISSUE TITLE
Metadata lang should be in ISO-639-3 format

### ISSUE THREAD

**Issue by kelson42** [kiwix/sotoki#21]
Here it is:
https://en.wikipedia.org/wiki/ISO_639-3

... and without "local" part

For now it seems to be ISO-639-2 with local/country part.

**Comment by dattaz** [comment]
We haven't information of language of question in stackexchange website and it's seem that all site of stackexchange are in english, so I think we can juste hardcoding language into the script. Are you ok with that ? (otherwise we can juste add option when you call script)

**Comment by dattaz** [comment]
Close by #32
