### ISSUE TITLE
Create default index.html

### ISSUE THREAD

**Issue by kelson42** [kiwix/sotoki#4]
I have launched a first dump and the result is available here:
http://zimfarm.kiwix.org/sotoki/

Unfortunately there is no (default) welcome page like:
http://zimfarm.kiwix.org/sotoki/index.html

This page might for example propose a cloud of tags but other ideas would be for sure doable.

**Comment by amirouche** [comment]
My plan is to use the tag index page.

**Comment by kelson42** [comment]
Yes, make sense. Then probably creating /index.html pointing to it would help.

**Comment by amirouche** [comment]
Ok.

**Comment by amirouche** [comment]
I did not link the commit, but this is done. The only problem is that **the page is big**. I'm not convinced this will work on small devices, but I may be wrong.

**Comment by amirouche** [comment]
fixed in b77f66fb2ee4d9900dde3a1941046576d65799b4
