### ISSUE TITLE
Generate zim files with html files

### ISSUE THREAD

**Issue by amirouche** [kiwix/sotoki#9]
Need also to run a script to offline images.

**Comment by amirouche** [comment]
@kelson42 can you point me to the correct documentation to generate zim files. Also you told me you have a script to rewrite HTML with offline versions of images.

After that step done, and if you agree we can declare the beta milestone done.

**Comment by amirouche** [comment]
the alpha milestone sorry.

**Comment by amirouche** [comment]
zimwriterfs can be found at: http://www.openzim.org/wiki/Build_your_ZIM_file#zimwriterfs

**Comment by kelson42** [comment]
You should find everything you need here: https://git.wikimedia.org/tree/openzim/HEAD/zimwriterfs

**Comment by kelson42** [comment]
zimwriterfs does all the necessary (for the ZIM file) URL rewriting. That said the HTML files stored on the fs need first to work perfectly locally. You can check this by open the HTML files with your favorie browser.

**Comment by dattaz** [comment]
Close by #32
